/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * PitStop.API
 * OpenAPI spec version: 1.0
 */
import type { WeatherForecast } from "../../types"

import { pitstopApiInstance } from "../../pitstopApiInstance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getWeatherForecastService = () => {
  const getWeatherForecast = (options?: SecondParameter<typeof pitstopApiInstance>) => {
    return pitstopApiInstance<WeatherForecast[]>(
      { url: `/WeatherForecast`, method: "GET" },
      options,
    )
  }
  return { getWeatherForecast }
}
export type GetWeatherForecastResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getWeatherForecastService>["getWeatherForecast"]>>
>
