/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * PitStop.API
 * OpenAPI spec version: 1.0
 */

export interface WeatherForecast {
  date?: string
  temperatureC?: number
  readonly temperatureF?: number
  /** @nullable */
  summary?: string | null
}
