// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PitStop.Core;

#nullable disable

namespace PitStop.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250717205701_CreateCustomerTable")]
    partial class CreateCustomerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PitStop.Core.Entities.Customer", b =>
                {
                    b.Property<long>("CusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cus_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CusId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<short?>("CusTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("cus_type_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Gdpr")
                        .HasColumnType("boolean")
                        .HasColumnName("gdpr");

                    b.Property<bool?>("GdprAllowAnalyticFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("gdpr_allow_analytic_flag");

                    b.Property<bool?>("GdprAllowCallFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("gdpr_allow_call_flag");

                    b.Property<bool?>("GdprAllowEmailFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("gdpr_allow_email_flag");

                    b.Property<bool?>("GdprAllowLetterFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("gdpr_allow_letter_flag");

                    b.Property<bool?>("GdprAllowSmsFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("gdpr_allow_sms_flag");

                    b.Property<DateTime?>("GdprDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gdpr_date");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.HasKey("CusId");

                    b.HasIndex("Lastname");

                    b.HasIndex("Mobile");

                    b.HasIndex("Telephone");

                    b.ToTable("customer");
                });
#pragma warning restore 612, 618
        }
    }
}
